version: '3.8'
services:
  php:
    build: ./php
    stdin_open: true
    tty: true
    networks:
      - backend
    volumes:
      - ./ssscientific_backend:/var/www/html
  apache:
    build: ./apache
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "9000:80"
    volumes:
      - ./ssscientific_backend:/var/www/html
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password@123
      - MYSQL_DATABASE=db_ssscientific
      - MYSQL_USER=ssscientific
      - MYSQL_PASSWORD=password@123
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - backend
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
    networks:
      - backend
    depends_on:
      - mysql
networks:
  frontend:
  backend: